export const cumplimientoONAVIPNV3 = [{
    "total": 15,
    "concluida": 12,
    "enProceso": 2,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "CONAVI",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 6,
    "concluida": 4,
    "enProceso": 1,
    "sinRealizar": 1,
    "porIniciar": 0,
    "organismo": "CONAVI",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 7,
    "concluida": 5,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "CONAVI",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 0,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "CONAVI",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 4,
    "concluida": 3,
    "enProceso": 0,
    "sinRealizar": 1,
    "porIniciar": 0,
    "organismo": "CONAVI",
    "tipoObjetivo": 5,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "FOVISSSTE",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "FOVISSSTE",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "FOVISSSTE",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 3,
    "concluida": 0,
    "enProceso": 2,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "FOVISSSTE",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "FOVISSSTE",
    "tipoObjetivo": 5,
    "trimestre": 3,
},{
    "total": 5,
    "concluida": 1,
    "enProceso": 4,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INFONAVIT",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 7,
    "concluida": 0,
    "enProceso": 5,
    "sinRealizar": 0,
    "porIniciar": 2,
    "organismo": "INFONAVIT",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 2,
    "concluida": 1,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INFONAVIT",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 3,
    "concluida": 1,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "INFONAVIT",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 2,
    "concluida": 0,
    "enProceso": 2,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INFONAVIT",
    "tipoObjetivo": 5,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INSUS",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INSUS",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 0,
    "concluida": 0,
    "enProceso": 0,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INSUS",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 0,
    "concluida": 0,
    "enProceso": 0,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "INSUS",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 10,
    "concluida": 3,
    "enProceso": 6,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "INSUS",
    "tipoObjetivo": 5,
    "trimestre": 3,
},{
    "total": 3,
    "concluida": 0,
    "enProceso": 2,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "SEDATU",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 11,
    "concluida": 0,
    "enProceso": 6,
    "sinRealizar": 0,
    "porIniciar": 5,
    "organismo": "SEDATU",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 2,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 1,
    "organismo": "SEDATU",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 2,
    "concluida": 1,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SEDATU",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 12,
    "concluida": 1,
    "enProceso": 7,
    "sinRealizar": 1,
    "porIniciar": 3,
    "organismo": "SEDATU",
    "tipoObjetivo": 5,
    "trimestre": 3,
},{
    "total": 3,
    "concluida": 0,
    "enProceso": 3,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SHF",
    "tipoObjetivo": 1,
    "trimestre": 3,
},{
    "total": 2,
    "concluida": 1,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SHF",
    "tipoObjetivo": 2,
    "trimestre": 3,
},{
    "total": 1,
    "concluida": 0,
    "enProceso": 1,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SHF",
    "tipoObjetivo": 3,
    "trimestre": 3,
},{
    "total": 0,
    "concluida": 0,
    "enProceso": 0,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SHF",
    "tipoObjetivo": 4,
    "trimestre": 3,
},{
    "total": 0,
    "concluida": 0,
    "enProceso": 0,
    "sinRealizar": 0,
    "porIniciar": 0,
    "organismo": "SHF",
    "tipoObjetivo": 5,
    "trimestre": 3,
}
]


