export const objs = {
    Objetivo1: [
        {
            "Acción puntual": "1.1.1 Promover la creación de una “canasta básica de elementos para la construcción de la vivienda",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.2 Homologar diferentes sistemas de información y tecnología existentes para ajustar los lineamientos del sector de la vivienda a las características que debe cumplir una vivienda adecuada, así como a las necesidades prioritarias de poblaciones indígenas, jefas de familia, personas con discapacidad, adultos mayores y jóvenes",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI, INFONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.3 Elaborar y difundir lineamientos técnicos respecto a una vivienda adecuada, con criterios específicos sobre materiales en pisos, techos y muros, esquemas de construcción y acceso a servicios básicos, que reconozcan la condición cultural y espacial de cada región para su aplicación por parte de todos los actores en el sistema de vivienda",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.4 Realizar estudios sobre el desarrollo de vivienda que se adecúe a los usos y costumbres de diferentes grupos, para informar el desarrollo de pruebas de implementación en los que se evalúe su producción a escala",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.5 Ofrecer más facilidades de pago para los créditos y financiamientos con los que cuentan las personas",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.6 Difundir Normas Oficiales Mexicanas (NOMs) para asegurar que el desarrollo de la vivienda se adecúe a las características de las distintas zonas bioclimáticas en el país",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.7 Impulsar acciones de mejoramiento y ampliación de la vivienda que se focalicen en grupos en condiciones de vulnerabilidad, respetando las condiciones culturales y espaciales de cada región y, en su caso, promoviendo la innovación con modelos constructivos y de diseño que se adapten a las necesidades de las personas y familias",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU, SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.8 Impulsar el uso de ecotecnias, particularmente en sitios de rezago habitacional donde existe una falta de disponibilidad de servicios",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.9 Impulsar acciones o programas de asistencia jurídica, con la participación de los gobiernos de las entidades federativas y de los municipios que faciliten la escrituración de las viviendas, con especial énfasis en poblaciones vulnerables que no tienen acceso a asesoría legal para su realización",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.1 Apoyar, a través de mecanismos de financiamiento, a las viviendas con mayor rezago",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, SHF, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.2 Revisar y replantear programas de mejora estructural, de reemplazo de techos, muros y pisos, y de terminación de vivienda, de acuerdo con lineamientos técnicos para una vivienda adecuada",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF, CONAVI, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.3 Promover asesorías de diseño y construcción de soluciones de ampliación y optimización del espacio en viviendas en situación de hacinamiento; incluyendo apoyo en la instalación de técnicas para el reciclaje de agua de lluvia y el aprovechamiento de fuentes renovables de energía",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.4 Apoyar acciones de mejoramiento integral en Unidades Habitacionales intraurbanas",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.1 Desarrollar instrumentos que incentiven el desarrollo de programas y proyectos habitacionales distintas a la adquisición, por ejemplo: cooperativas de vivienda, vivienda en renta, alquiler con opción a compra, lotes con servicios, entre otros",
            "Tipo de acción Puntual": "Coordinación de la estrategia ",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.2 Diseñar soluciones que ayuden a prevenir y, en su caso, brindar condiciones justas, para la población en condiciones de vulnerabilidad en asentamientos irregulares, con base en estudios que permitan la progresividad en autoproducción de vivienda y urbanización",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.3 Proveer asistencia técnica integral para la autoproducción de vivienda, buscando garantizar la participación de las personas en la toma de decisiones para aprovechar óptimamente sus recursos económicos, sociales y en especie",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.4 Colaborar con estados y municipios para identificar alternativas de vivienda adecuada distintas a la adquisición, que tengan viabilidad económica y social en ciudades o polígonos específicos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.5 Colaborar con estados y municipios para apoyar los procesos de autoproducción de vivienda, procurando que se lleven a cabo de forma que aseguren la calidad estructural, constructiva y de diseño",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.1 Diseñar un modelo mixto que mejore la asequibilidad de todo tipo de soluciones de vivienda, siempre y cuando ésta cumpla con los elementos de una vivienda adecuada",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.2 Otorgar subsidios mediante programas de regularización de lotes habitacionales que contribuyan al otorgamiento de certeza jurídica a la población que se encuentra en condiciones de rezago",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "1.4.3 Reorientar los esquemas de subsidios para apoyar a la población no afiliada, obedeciendo a la demanda real a nivel nacional",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.4 Focalizar la política de subsidios hacia sectores de menores ingresos, en condiciones de rezago o grupos históricamente discriminados (mujeres, personas con discapacidad, adultos mayores, jóvenes0)",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.5 Promover, diseñar e implementar acciones e instrumentos específicos que incrementen el acceso a subsidios dirigidos particularmente a mujeres, personas con discapacidad, adultos mayores, jóvenes y otros grupos en condiciones históricamente discriminados (Indígenas, etnias y afrodescendientes)",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.6 Brindar apoyo y capacitación a proveedores locales de materiales, vigilando también que éstos no incurran en prácticas que mermen la asequibilidad de la vivienda",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.1 Diseñar esquemas financieros y de ahorro para ampliar la cobertura de soluciones de vivienda",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI, SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.2 Instrumentar lineamientos financieros que requieran esquemas de créditos hipotecarios, cofinanciamiento y ahorro previo dirigidos a la población no afiliada y en situación de vulnerabilidad",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI, SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.3 Ampliar el Programa Responsabilidad Compartida y las estrategias de conversión de créditos de Veces Salarios Mínimos (VSM) a pesos",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.4 Ampliar la oferta de soluciones financieras dirigidas a grupos de población específicos que por sus características laborales y económicas no cumplen con las condiciones prevalentes para la solicitud de un crédito INFONAVIT",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.5 Ofrecer una alternativa de financiamiento y asesoría técnica para autoproducción de vivienda del INFONAVIT, que represente un financiamiento asequible, accesible y adecuado a las necesidades y posibilidades del derechohabiente",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.6 Ofrecer productos financieros en conjunto con otros organismos, con el propósito de maximizar su capacidad crediticia para la adquisición de una vivienda nueva o usada de mejor calidad",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF, FOVISSSTE, INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.7 Otorgar créditos hipotecarios bajo nuevos esquemas crediticios, alineados a las necesidades de los derechohabientes más vulnerables, para adquisición de vivienda nueva o usada, reparación, ampliación o mejoramiento de vivienda, construcción y redención de pasivos",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "FOVISSSTE, SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.8 Establecer criterios de priorización en el otorgamiento de créditos hipotecarios, para favorecer a viviendas en sectores de menores ingresos o en condiciones de rezago",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF, INFONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.9 Premiar a derechohabientes que cumplan puntualmente en el pago de sus créditos",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.10 Colaborar con la banca de desarrollo y la banca comercial en la flexibilización de productos financieros dirigidos a la vivienda (p.ej. micro financiamientos hipotecarios) para diseñar e implementar apoyos que pueda otorgar el Estado para tal fin (p.ej. garantías)",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.6.1 Difundir entre los gobiernos estatales y municipales los programas de producción social de vivienda, enfatizando criterios de calidad y sustentabilidad para generar soluciones progresivas y flexibles enfocadas en poblaciones en condiciones de rezago",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.6.2 Identificar las viviendas con mayor rezago y focalizar en ellas inversiones en acciones de mejoramiento, ampliación y substitución; todo ello haciendo uso de materiales locales de buena calidad, así como mejorando su acceso a servicios básicos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF, CONAV",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ],
    Objetivo2: [
        {
            "Acción puntual": "2.1.1 Promover la creación de una canasta básica de elementos para la construcción de la vivienda",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.2 Realizar convenios intersectoriales en coparticipación con el sector público en sus tres niveles de gobierno, para que, a través de Fideicomisos de desarrollo inmobiliario, se genere oferta de vivienda adecuada, con identidad y dinamizando la actuación comunitaria de grupos de ahorro para vivienda o infraestructura",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.3 Implementar, por medio de convenios, una ventanilla única de servicios que fomente la simplificación administrativa de los trámites y servicios que brindan los ONAVIS",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.4 Desarrollar soluciones digitales y analíticas que optimicen los procesos y reduzcan los costos de los procedimientos de los ONAVIS requeridos durante el proceso de otorgamiento de créditos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.5 Implementar una nueva estrategia de gestión de la cartera y un nuevo modelo de cobranza en el INFONAVIT",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.6 Buscar y promover la innovación financiera de los organismos nacionales de vivienda",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.1 Desarrollar un modelo de cobertura y atención de los ONAVIs y otros participantes del sector de la vivienda que esté enfocado en atender las necesidades de los grupos en condición de vulnerabilidad y de las zonas con mayor grado de marginación y altos índices de violencia",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.2 Establecer instrumentos de seguimiento y monitoreo, al menos de forma anual, para dar seguimiento a las acciones de vivienda, así como los acuerdos y responsabilidades de los organismos nacionales de vivienda",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.3 Establecer mecanismos de colaboración entre los ONAVIS para que la política de vivienda contenga el enfoque de derechos humanos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.4 Promover mejoras al marco normativo y jurídico de las instituciones, de forma que sean adecuadas para cubrir las necesidades de vivienda identificadas",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.5 Promover, a través de los gobiernos municipales, intervenciones para la regularización de la tenencia de la tierra urbana",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.1 Elaborar un plan de acción que estudie y proponga acciones coordinadas entre los ONAVIs para prevenir el abandono y deterioro de viviendas",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.2 Implementar un programa de recuperación de la vivienda abandonada, deshabitada y deteriorada, que establezca métodos claros para identificar los casos y seleccionar soluciones de intervención según las necesidades",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.3 Desarrollar e incluir los planes y programas de desarrollo urbano y sus modificaciones en el Sistema de Información Territorial y Desarrollo Urbano",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.4 Coordinar las acciones y subsidios a la vivienda con las intervenciones de la SEDATU en barrios que requieren mejoramiento urbano y atender las necesidades de la vivienda en rezago",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.5 Proponer y promover la incorporación de nuevas Instituciones financieras bancarias y no bancarias a fin de aumentar y mejorar las condiciones de financiamiento a los sectores prioritarios.",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.6 Fomentar la mejora urbana y el acceso de las viviendas a equipamiento por parte de los tres órdenes de gobierno",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.1 Instrumentar mecanismos de seguimiento y acompañamiento a municipios para promover la nueva Política de Vivienda a nivel local",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.2 Implementar mecanismos para dar seguimiento puntual al cumplimiento de las reglas de operación existentes respecto al manejo de los recursos federales ejecutados por los gobiernos municipales",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.3 Brindar capacitación y asesoría técnica a gobiernos estatales y municipales para que integren los conceptos de vivienda adecuada a sus políticas e instrumentos de planeación",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.4 Incentivar la colocación de créditos en municipios que tengan instrumentos legales de planeación y/o catastro vigentes",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.5 Apoyar a solicitud de los Gobiernos Locales en la elaboración, difusión e implementación de programas de vivienda en los gobiernos estatales y municipales que actualmente carezcan de uno",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.6 Generar y difundir incentivos para que los gobiernos locales se unan al Programa de Modernización de los Registros Públicos de la Propiedad y Catastros",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.7 Promover la revisión, el seguimiento técnico y, en su caso, la modificación de los programas de vivienda existentes a nivel local a través de convenios de coordinación, para garantizar que estén alineados a la nueva política de vivienda",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.8 Fomentar el fortalecimiento de las acciones de los Organismos Estatales de Vivienda (OREVIS) y de los gobiernos municipales, a través de capacitación técnica para las acciones de mejoramiento y producción social de vivienda asistida",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.1 Desarrollar nuevos productos de solución que permitan resolver un mayor número de créditos con adeudo vencido y así disminuir la cartera vencida",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.2 Promover una Norma Oficial Mexicana de Vivienda Adecuada",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.3 Promover una Norma Oficial Mexicana para la Vivienda que introduzca los lineamientos necesarios en materia de instalaciones de agua, luz y gas, así como dimensiones mínimas para los elementos de la vivienda, e incorpore las disposiciones de la Norma Mexicana de Edificación Sustentable",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.4 Promover la aplicación del Código de Edificación de Vivienda (CEV) como marco normativo para acciones de vivienda que reciben créditos o subsidios federales",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.5 Promover acciones para reducir los costos en los que incurren las personas respecto a los trámites y procedimientos relacionados al otorgamiento de créditos",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ],
    Objetivo3: [
        {
            "Acción puntual": "3.1.1 Establecer programas de asistencia e incentivos a productores locales pequeños y medianos, para que al integrarse de forma eficiente a las cadenas de suministro de la vivienda contribuyan a mejorar la asequibilidad y adecuación cultural de ésta",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.1.2 Establecer alianzas con las instituciones bancarias y organismos nacionales de vivienda, para promover nuevos mecanismos de financiamiento de créditos con garantía hipotecaria",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual":"3.1.3 Crear programas integrales, a través de convenios de coparticipación de los tres órdenes de gobierno y el sector privado, para el desarrollo de vivienda asequible y con una mejor ubicación, fortaleciendo el tejido social y el arraigo", 
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.1.4 Evaluar a todas aquellas entidades financieras que puedan participar como Entidades Ejecutoras, de forma que puedan canalizar apoyos para vivienda asequible usando enfoques participativos, solidarios y cooperativos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.1.5 Diseñar lineamientos para evaluar los modelos de vivienda aprobados e implementados en los municipios, que tomen en cuenta la estructura, localización y accesibilidad",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.2.1 Participar en las mesas de colaboración con los actores privados y sociales, para que brinden sus perspectivas en la actualización de los lineamientos y criterios técnicos que guiarán el desarrollo y promoción de la vivienda adecuada",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.2.2 Promover encuentros regionales y nacionales para el intercambio de experiencias entre los actores del sistema de vivienda, facilitando la difusión de técnicas que agilicen la aplicación de nuevos criterios y lineamientos técnicos",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.2.3 Promover la innovación a través de concursos nacionales de vivienda, donde los ejes temáticos se relacionen con los lineamientos técnicos que se busca promover para la provisión de una vivienda adecuada (con enfoque de género, adecuación cultural, diseño vernáculo, entre otros)",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.3.1 Difundir acciones que promuevan entre actores privados y sociales prácticas eficientes transparentes en la gestión y difusión de sus proyectos ",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.3.2 Generar incentivos a la banca comercial y a la banca de desarrollo para ampliar la cobertura de financiamientos a grupos en condición de vulnerabilidad, por ejemplo, a través de tasas preferenciales",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SHF",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.3.3 Promover alianzas estratégicas con organizaciones sociales y comunitarias, incluyendo a instituciones de educación superior, para formar especialistas y realizar investigaciones sobre vivienda y habitabilidad",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "3.3.4 Promover programas de formación y capacitación para asistentes técnicos y para los capacitadores respecto a la producción social de vivienda asistida",
            "Tipo de acción Puntual": "General",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ],
    Objetivo4: [
        {
            "Acción puntual": "4.1.1 Celebrar convenios con los Registros Públicos para obtener documentación faltante o deficiente en los créditos en cobranza judicial, permitiendo su ejecución de una manera más eficiente",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.1.2 Revisar los casos judiciales en los que existieron irregularidades y con ello evitar desalojos injustificados",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.1.3 Coordinar esfuerzos con los ONAVIS para difundir, entre todas las personas, información actualizada y completa sobre las soluciones de vivienda existentes y los apoyos disponibles para acceder a ellas (incluyendo los resultados de la ENVI)",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.1.4 Apoyar a los miembros del sistema de vivienda en la generación de información sobre procesos y trámites de construcción, materiales y políticas de comercialización, de manera que se propongan e impulsen mejoras",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.2.1 Promover ante la PROFECO la revisión de los proveedores de materiales de construcción, para asegurar calidad y prevenir abusos en precios (sobre todo en medidas de autoconstrucción y reconstrucción tras los sismos)",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.3.1 Mantener actualizado el instrumento de seguimiento de proveedores de vivienda en donde exista visibilidad de los propietarios de las empresas, para inhibir malas prácticas y promover la eficiencia y calidad",
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "INFONAVIT, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "4.3.2 Desarrollar un programa de capacitación dirigido a personas con una función gubernamental dentro del sector de vivienda en materia de transparencia y rendición de cuentas, el cual les brinde las herramientas para detectar y denunciar actos de corrupción", 
            "Tipo de acción Puntual": "Específica",
            "Dependencias y/o Entidades responsables de instrumentar la acción puntual (Instituciones Coordinadas)": "FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ],
    Objetivo5: [
        {
            "Acción puntual": "5.1.1 Realizar un levantamiento a nivel nacional para caracterizar la problemática de vivienda informal y de vivienda abandonada; complementándolo con estudios que, desde enfoques interdisciplinarios, permitan entender mejor ambas problemáticas y así diseñar soluciones de atención que las mitiguen y prevengan",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.1.2 Actualizar el inventario nacional de suelo para identificar suelo apropiado para el desarrollo de vivienda, tanto en zonas urbanas como rurales, privilegiando terrenos en zonas consolidadas con acceso a fuentes de empleo y servicios",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.1.3 Llevar a cabo el proceso de diseño técnico y metodológico para elaborar el registro de asentamientos irregulares que sean objeto de las acciones de vivienda de las instituciones competentes.",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.1.4 Rediseñar el RENARET y elaborar nuevos lineamientos para su funcionamiento, analizando estrategias para incrementar y gestionar adecuadamente el uso de reservas territoriales del Estado y las pertenecientes al sector, con el fin de poder ofrecer mayor disponibilidad de vivienda asequible para la población en mayor rezago",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.1.5 Fomentar la actualización catastral y registral como apoyo para identificar y valorar suelo vacante o subutilizado, a fin de integrar reservas estratégicas de suelo para vivienda",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.1.6 Asegurar que en los procesos de apoyo técnico a los PMDUs, se integren criterios y capacitaciones para promover zonas habitacionales con disponibilidad de servicios y buena ubicación, sensibilizando además respecto a la importancia de usos mixtos y proximidad al transporte público",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.1.7 Promover la integración del Sistema de Información Territorial y Urbano para que se incorporen datos espaciales y estadísticos de ubicación relativos con: áreas prioritarias de desarrollo, zonas de riesgo, áreas naturales protegidas y zonas de patrimonio histórico, para contribuir a la planificación urbana y territorial de los municipios",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU, INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.1.8 Coordinar la articulación de los programas de vivienda con los de movilidad y transporte, tomando en cuenta la localización de la vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.2.1 Generar mecanismos e instrumentos normativos que propicien la redensificación habitacional al interior de las ciudades, respetando la capacidad de carga y alineando la política crediticia con el modelo de ciudad, compacta o conectada establecido por cada una de ellas.", 
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.2.2 Desarrollar mecanismos e instrumentos de coordinación y participación con los municipios, para impulsar proyectos de gestión de suelo vacante o subutilizado que promuevan acciones de vivienda y usos complementarios.",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.2.3 Integrar un formato de diagnóstico que considere la información de los Perímetros de Contención Urbana (PCU) como apoyo y referente para asegurar una adecuada ubicación de toda vivienda apoyada por subsidios y financiamientos del Estado, perfeccionando el diseño y proceso de aplicación de los mismos.",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.2.4 Incentivar la colocación de hipotecas en los Perímetros de Contención Urbana 1 y 2 para promover la ocupación y recuperación de centros históricos o zonas centrales, minimizando la probabilidad de abandono y disminuyendo la dependencia de vehículos particulares.",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT, FOVISSSTE",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.2.5 Impulsar proyectos de desarrollo de uso mixto en suelo dirigido a vivienda adecuada, que cumplan con criterios de ubicación y acceso a oportunidades de empleo, infraestructura, servicios y soluciones de movilidad",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.2.6 Priorizar el otorgamiento de subsidios, en función de la existencia de planes y proyectos de movilidad sustentable en estados y municipios; favoreciendo la conexión entre el transporte público y la vivienda para la población de menores ingresos",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.2.7 Promover programas y acciones de vivienda, bajo un modelo de redensificación de ciudad compacta, conectada e integrada.", 
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.3.1 Implementar programas para la regularización de la tenencia de la tierra para contribuir al desarrollo de vivienda sustentable", 
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.3.2 Elaborar un diagnóstico de la tenencia de la tierra en la periferia de las ciudades, como apoyo a las acciones de vivienda, gestión de suelo, gestión de riesgos y ordenamiento territorial.",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.3.3 Promover la Política Nacional de Suelo a través de proyectos urbanos soportados por instrumentos de gestión de suelo, orientados en atender las necesidades de vivienda nueva y usos urbanos complementarios.",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.3.4 Desarrollar instrumentos de colaboración y coordinación entre diferentes actores sociales, públicos y privados para incorporar suelo a proyectos urbanos y rurales de manera sustentable",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "5.3.5 Reconfigurar los Perímetros de Contención Urbana para alinear el instrumento a la nueva Política de Vivienda y de Desarrollo Urbano",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.3.6 Coordinar con las dependencias de la Administración Pública Federal y los gobiernos locales, acciones para otorgar certeza jurídica sobre la vivienda y así garantizar la seguridad patrimonial de las personas",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.1 Elaborar mecanismos de coordinación y colaboración entre dependencias federales, estatales y municipales para la previsión de suelo apto y bien localizado destinado a la reubicación de asentamientos humanos que se encuentran en zonas de alto riesgo y alto valor ecológico",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.2 Diseñar y ejecutar limitaciones en el otorgamiento de subsidios federales a desarrollos en zonas catalogadas como de conservación o alto riesgo",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.3 Mejorar la calidad de la asistencia técnica a municipios afectados por desastres derivados de fenómenos naturales mediante técnicos mejor capacitados sobre las acciones puntuales de los programas que instrumenta la CONAVI", 
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.4 Brindar asistencia técnica a estados y municipios para fortalecer la revisión y verificación de sus proyectos de expansión urbana y de desarrollo de vivienda, para asegurar que incluyan un enfoque de manejo integral del riesgo",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.5 Coordinar con el CENAPRED la generación de información geoestadística sobre la vulnerabilidad de las viviendas por su ubicación y tipo de construcción ante eventos perturbadores, que esté vinculado a los Programas Municipales de Desarrollo Urbano (PMDUs)",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.6 Coordinar con el CENAPRED la difusión de información a la población vulnerable respecto a eventos perturbadores y posibles riesgos, así como las mejores prácticas de construcción para mitigarlos", 
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "5.4.7 Promover el uso de Atlas de Riesgo como herramienta para orientar la ubicación de las acciones de vivienda y que con ello sea un instrumento útil en la toma de decisiones en la materia.",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "Dependencia o Entidad Coordinadora (Encargada del seguimiento)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        
    ]
}