export const objs = {
    Objetivo1: [
    	{
            "Acción puntual": "1.1.1 Promover la creación de una “canasta básica de elementos para la construcción de la vivienda",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.2 Homologar diferentes sistemas de información y tecnología existentes para ajustar los lineamientos del sector de la vivienda a las características que debe cumplir una vivienda adecuada, así como a las necesidades prioritarias de poblaciones indígenas, jefas de familia, personas con discapacidad, adultos mayores y jóvenes",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI, INFONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.3 Elaborar y difundir lineamientos técnicos respecto a una vivienda adecuada, con criterios específicos sobre materiales en pisos, techos y muros, esquemas de construcción y acceso a servicios básicos, que reconozcan la condición cultural y espacial de cada región para su aplicación por parte de todos los actores en el sistema de vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.4 Realizar estudios sobre el desarrollo de vivienda que se adecúe a los usos y costumbres de diferentes grupos, para informar el desarrollo de pruebas de implementación en los que se evalúe su producción a escala",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.5 Ofrecer más facilidades de pago para los créditos y financiamientos con los que cuentan las personas",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.6 Difundir Normas Oficiales Mexicanas (NOMs) para asegurar que el desarrollo de la vivienda se adecúe a las características de las distintas zonas bioclimáticas en el país",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.7 Impulsar acciones de mejoramiento y ampliación de la vivienda que se focalicen en grupos en condiciones de vulnerabilidad, respetando las condiciones culturales y espaciales de cada región y, en su caso, promoviendo la innovación con modelos constructivos y de diseño que se adapten a las necesidades de las personas y familias",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU, SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.8 Impulsar el uso de ecotecnias, particularmente en sitios de rezago habitacional donde existe una falta de disponibilidad de servicios",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.1.9 Impulsar acciones o programas de asistencia jurídica, con la participación de los gobiernos de las entidades federativas y de los municipios que faciliten la escrituración de las viviendas, con especial énfasis en poblaciones vulnerables que no tienen acceso a asesoría legal para su realización",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.1 Apoyar, a través de mecanismos de financiamiento, a las viviendas con mayor rezago",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT, SHF, FOVISSSTE",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.2 Revisar y replantear programas de mejora estructural, de reemplazo de techos, muros y pisos, y de terminación de vivienda, de acuerdo con lineamientos técnicos para una vivienda adecuada",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF, CONAVI, FOVISSSTE",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.3 Promover asesorías de diseño y construcción de soluciones de ampliación y optimización del espacio en viviendas en situación de hacinamiento; incluyendo apoyo en la instalación de técnicas para el reciclaje de agua de lluvia y el aprovechamiento de fuentes renovables de energía",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.2.4 Apoyar acciones de mejoramiento integral en Unidades Habitacionales intraurbanas",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.1 Desarrollar instrumentos que incentiven el desarrollo de programas y proyectos habitacionales distintas a la adquisición, por ejemplo: cooperativas de vivienda, vivienda en renta, alquiler con opción a compra, lotes con servicios, entre otros",
            "Tipo de acción Puntual": "Coordinación de la estrategia ",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.2 Diseñar soluciones que ayuden a prevenir y, en su caso, brindar condiciones justas, para la población en condiciones de vulnerabilidad en asentamientos irregulares, con base en estudios que permitan la progresividad en autoproducción de vivienda y urbanización",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.3 Proveer asistencia técnica integral para la autoproducción de vivienda, buscando garantizar la participación de las personas en la toma de decisiones para aprovechar óptimamente sus recursos económicos, sociales y en especie",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.4 Colaborar con estados y municipios para identificar alternativas de vivienda adecuada distintas a la adquisición, que tengan viabilidad económica y social en ciudades o polígonos específicos",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.3.5 Colaborar con estados y municipios para apoyar los procesos de autoproducción de vivienda, procurando que se lleven a cabo de forma que aseguren la calidad estructural, constructiva y de diseño",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.1 Diseñar un modelo mixto que mejore la asequibilidad de todo tipo de soluciones de vivienda, siempre y cuando ésta cumpla con los elementos de una vivienda adecuada",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.2 Otorgar subsidios mediante programas de regularización de lotes habitacionales que contribuyan al otorgamiento de certeza jurídica a la población que se encuentra en condiciones de rezago",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano, QDV - Instituto Nacional del Suelo Sustentable",
        },
        {
            "Acción puntual": "1.4.3 Reorientar los esquemas de subsidios para apoyar a la población no afiliada, obedeciendo a la demanda real a nivel nacional",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.4 Focalizar la política de subsidios hacia sectores de menores ingresos, en condiciones de rezago o grupos históricamente discriminados (mujeres, personas con discapacidad, adultos mayores, jóvenes0)",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.5 Promover, diseñar e implementar acciones e instrumentos específicos que incrementen el acceso a subsidios dirigidos particularmente a mujeres, personas con discapacidad, adultos mayores, jóvenes y otros grupos en condiciones históricamente discriminados (Indígenas, etnias y afrodescendientes)",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT, CONAV",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.4.6 Brindar apoyo y capacitación a proveedores locales de materiales, vigilando también que éstos no incurran en prácticas que mermen la asequibilidad de la vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.1 Diseñar esquemas financieros y de ahorro para ampliar la cobertura de soluciones de vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI, SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.2 Instrumentar lineamientos financieros que requieran esquemas de créditos hipotecarios, cofinanciamiento y ahorro previo dirigidos a la población no afiliada y en situación de vulnerabilidad",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI, SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.3 Ampliar el Programa Responsabilidad Compartida y las estrategias de conversión de créditos de Veces Salarios Mínimos (VSM) a pesos",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.4 Ampliar la oferta de soluciones financieras dirigidas a grupos de población específicos que por sus características laborales y económicas no cumplen con las condiciones prevalentes para la solicitud de un crédito INFONAVIT",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.5 Ofrecer una alternativa de financiamiento y asesoría técnica para autoproducción de vivienda del INFONAVIT, que represente un financiamiento asequible, accesible y adecuado a las necesidades y posibilidades del derechohabiente",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.6 Ofrecer productos financieros en conjunto con otros organismos, con el propósito de maximizar su capacidad crediticia para la adquisición de una vivienda nueva o usada de mejor calidad",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF, FOVISSSTE, INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.7 Otorgar créditos hipotecarios bajo nuevos esquemas crediticios, alineados a las necesidades de los derechohabientes más vulnerables, para adquisición de vivienda nueva o usada, reparación, ampliación o mejoramiento de vivienda, construcción y redención de pasivos",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "FOVISSSTE, SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.8 Establecer criterios de priorización en el otorgamiento de créditos hipotecarios, para favorecer a viviendas en sectores de menores ingresos o en condiciones de rezago",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF, INFONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.9 Premiar a derechohabientes que cumplan puntualmente en el pago de sus créditos",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.5.10 Colaborar con la banca de desarrollo y la banca comercial en la flexibilización de productos financieros dirigidos a la vivienda (p.ej. micro financiamientos hipotecarios) para diseñar e implementar apoyos que pueda otorgar el Estado para tal fin (p.ej. garantías)",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.6.1 Difundir entre los gobiernos estatales y municipales los programas de producción social de vivienda, enfatizando criterios de calidad y sustentabilidad para generar soluciones progresivas y flexibles enfocadas en poblaciones en condiciones de rezago",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "1.6.2 Identificar las viviendas con mayor rezago y focalizar en ellas inversiones en acciones de mejoramiento, ampliación y substitución; todo ello haciendo uso de materiales locales de buena calidad, así como mejorando su acceso a servicios básicos",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF, CONAV",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ],
    Objetivo2: [
        {
            "Acción puntual": "2.1.1 Promover la creación de una canasta básica de elementos para la construcción de la vivienda",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.2 Realizar convenios intersectoriales en coparticipación con el sector público en sus tres niveles de gobierno, para que, a través de Fideicomisos de desarrollo inmobiliario, se genere oferta de vivienda adecuada, con identidad y dinamizando la actuación comunitaria de grupos de ahorro para vivienda o infraestructura",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "FOVISSSTE",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.3 Implementar, por medio de convenios, una ventanilla única de servicios que fomente la simplificación administrativa de los trámites y servicios que brindan los ONAVIS",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.4 Desarrollar soluciones digitales y analíticas que optimicen los procesos y reduzcan los costos de los procedimientos de los ONAVIS requeridos durante el proceso de otorgamiento de créditos",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.5 Implementar una nueva estrategia de gestión de la cartera y un nuevo modelo de cobranza en el INFONAVIT",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.1.6 Buscar y promover la innovación financiera de los organismos nacionales de vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT, SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.1 Desarrollar un modelo de cobertura y atención de los ONAVIs y otros participantes del sector de la vivienda que esté enfocado en atender las necesidades de los grupos en condición de vulnerabilidad y de las zonas con mayor grado de marginación y altos índices de violencia",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.2 Establecer instrumentos de seguimiento y monitoreo, al menos de forma anual, para dar seguimiento a las acciones de vivienda, así como los acuerdos y responsabilidades de los organismos nacionales de vivienda",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.3 Establecer mecanismos de colaboración entre los ONAVIS para que la política de vivienda contenga el enfoque de derechos humanos",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.4 Promover mejoras al marco normativo y jurídico de las instituciones, de forma que sean adecuadas para cubrir las necesidades de vivienda identificadas",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.2.5 Promover, a través de los gobiernos municipales, intervenciones para la regularización de la tenencia de la tierra urbana",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INSUS",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.1 Elaborar un plan de acción que estudie y proponga acciones coordinadas entre los ONAVIs para prevenir el abandono y deterioro de viviendas",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.2 Implementar un programa de recuperación de la vivienda abandonada, deshabitada y deteriorada, que establezca métodos claros para identificar los casos y seleccionar soluciones de intervención según las necesidades",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.3 Desarrollar e incluir los planes y programas de desarrollo urbano y sus modificaciones en el Sistema de Información Territorial y Desarrollo Urbano",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.4 Coordinar las acciones y subsidios a la vivienda con las intervenciones de la SEDATU en barrios que requieren mejoramiento urbano y atender las necesidades de la vivienda en rezago",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.5 Proponer y promover la incorporación de nuevas Instituciones financieras bancarias y no bancarias a fin de aumentar y mejorar las condiciones de financiamiento a los sectores prioritarios.",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.3.6 Fomentar la mejora urbana y el acceso de las viviendas a equipamiento por parte de los tres órdenes de gobierno",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.1 Instrumentar mecanismos de seguimiento y acompañamiento a municipios para promover la nueva Política de Vivienda a nivel local",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.2 Implementar mecanismos para dar seguimiento puntual al cumplimiento de las reglas de operación existentes respecto al manejo de los recursos federales ejecutados por los gobiernos municipales",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.3 Brindar capacitación y asesoría técnica a gobiernos estatales y municipales para que integren los conceptos de vivienda adecuada a sus políticas e instrumentos de planeación",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.4 Incentivar la colocación de créditos en municipios que tengan instrumentos legales de planeación y/o catastro vigentes",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SHF",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.5 Apoyar a solicitud de los Gobiernos Locales en la elaboración, difusión e implementación de programas de vivienda en los gobiernos estatales y municipales que actualmente carezcan de uno",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.6 Generar y difundir incentivos para que los gobiernos locales se unan al Programa de Modernización de los Registros Públicos de la Propiedad y Catastros",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.7 Promover la revisión, el seguimiento técnico y, en su caso, la modificación de los programas de vivienda existentes a nivel local a través de convenios de coordinación, para garantizar que estén alineados a la nueva política de vivienda",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.4.8 Fomentar el fortalecimiento de las acciones de los Organismos Estatales de Vivienda (OREVIS) y de los gobiernos municipales, a través de capacitación técnica para las acciones de mejoramiento y producción social de vivienda asistida",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.1 Desarrollar nuevos productos de solución que permitan resolver un mayor número de créditos con adeudo vencido y así disminuir la cartera vencida",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT, FOVISSSTE",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.2 Promover una Norma Oficial Mexicana de Vivienda Adecuada",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "SEDATU",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.3 Promover una Norma Oficial Mexicana para la Vivienda que introduzca los lineamientos necesarios en materia de instalaciones de agua, luz y gas, así como dimensiones mínimas para los elementos de la vivienda, e incorpore las disposiciones de la Norma Mexicana de Edificación Sustentable",
            "Tipo de acción Puntual": "General",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.4 Promover la aplicación del Código de Edificación de Vivienda (CEV) como marco normativo para acciones de vivienda que reciben créditos o subsidios federales",
            "Tipo de acción Puntual": "Específica",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "CONAVI",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
        {
            "Acción puntual": "2.5.5 Promover acciones para reducir los costos en los que incurren las personas respecto a los trámites y procedimientos relacionados al otorgamiento de créditos",
            "Tipo de acción Puntual": "Coordinación de la estrategia",
            "DEPENDENCIAS Y/O ENTIDADES RESPONSABLES DE INSTRUMENTAR LA ACCIÓN PUNTUAL (INSTITUCIONES COORDINADAS": "INFONAVIT",
            "DEPENDENCIA O ENTIDAD COORDINADORA (ENCARGADA DEL SEGUIMIENTO)": "15 - Desarrollo Agrario, Territorial y Urbano",
        },
    ]
}
